name: packmate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Firebase core (for Flutter 3.19.6, compatible version)
  firebase_core: ^2.30.1

  # Firebase authentication
  firebase_auth: ^4.19.4

  # Cloud Firestore database
  cloud_firestore: ^4.17.5

  # Firebase Cloud Messaging (push notifications)
  firebase_messaging: ^14.9.1

  shared_preferences: ^2.1.1

  # Firebase Storage
  firebase_storage: ^11.6.9
  crypto: ^3.0.3
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  uuid: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1   # <--- Place it here

flutter:
  uses-material-design: true
  assets:
    - assets/logo/viago_logo.png     # <--- Add your image asset here
    - assets/images/viago_logo1.png
    - assets/images/login_image.png
    - assets/images/signup_image.png
    - assets/images/lock_symbol.png
    - assets/images/app_name.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/viago_logo.png"