// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJuJhAhgJ53WhvoBEctOADIpl7rcHR3w',
    appId: '1:727408607976:web:d40b7e90cb87fa87107f5d',
    messagingSenderId: '727408607976',
    projectId: 'viago-d308a',
    authDomain: 'viago-d308a.firebaseapp.com',
    storageBucket: 'viago-d308a.firebasestorage.app',
    measurementId: 'G-FLTN2YQHKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnADpqlrqG_2rgrydm_Bg49OTJEQaykfY',
    appId: '1:727408607976:android:becefd174b86a48a107f5d',
    messagingSenderId: '727408607976',
    projectId: 'viago-d308a',
    storageBucket: 'viago-d308a.firebasestorage.app',
  );

}